AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: API Gateway + Lambda to set branch protection on new GH repo

Parameters:
  Secret:
    Type: String
  GHToken:
    Type: String
  NotifyUser:
    Type: String
    ConstraintDescription: github user to mention
  EnforceAdmins:
    Type: String
    Default: false
    AllowedValues: [true, false]
  DismissStaleReviews:
    Type: String
    Default: false
    AllowedValues: [true, false]
  RequireCodeOwnerReviews:
    Type: String
    Default: false
    AllowedValues: [true, false]
  RequiredApprovingReviewCount:
    Type: Number
    Default: 1
  RequiredLinearHistory:
    Type: String
    Default: false
    AllowedValues: [true, false]
  AllowForcePushes:
    Type: String
    Default: false
    AllowedValues: [true, false]
  AllowDeletions:
    Type: String
    Default: false
    AllowedValues: [true, false]
  BlockCreations:
    Type: String
    Default: false
    AllowedValues: [true, false]
  RequiredConversationResolution:
    Type: String
    Default: false
    AllowedValues: [true, false]

Resources:
  processWebhookApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${AWS::StackName}-processWebhookApi
      StageName: Prod
      Cors: "'*'"
  processWebhook:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-processWebhook
      Description: processWebhook endpoint
      CodeUri: src/
      Handler: processWebhook/index.handler
      Runtime: nodejs16.x
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref processWebhookApi
            Path: /processWebhook
            Method: POST
      Environment:
        Variables:
          SECRET: !Ref Secret
          GH_TOKEN: !Ref GHToken
          NOTIFY_USER: !Ref NotifyUser
          ENFORCE_ADMINS: !Ref EnforceAdmins
          DISMISS_STALE_REVIEWS: !Ref DismissStaleReviews
          REQUIRE_CODE_OWNER_REVIEWS: !Ref RequireCodeOwnerReviews
          REQUIRED_APPROVING_REVIEW_COUNT: !Ref RequiredApprovingReviewCount
          REQUIRED_LINEAR_HISTORY: !Ref RequiredLinearHistory
          ALLOW_FORCE_PUSHES: !Ref AllowForcePushes
          ALLOW_DELETIONS: !Ref AllowDeletions
          BLOCK_CREATIONS: !Ref BlockCreations
          REQUIRED_CONVERSATION_RESOLUTION: !Ref RequiredConversationResolution


Outputs:
  processWebhookApiEndpoint:
    Description: API Gateway endpoint URL for Prod stage for processWebhook function
    Value: !Sub https://${processWebhookApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/processWebhook
