on:
  pull_request:
    types:
      - opened

jobs:
  deploy-new-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      # sam build 
      - run: sam build --use-container

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides Secret=${{ secrets.SECRET }} GHToken=${{ secrets.GH_TOKEN }} NotifyUser=${{ secrets.NOTIFY_USER }} EnforceAdmins=true DismissStaleReviews=true RequireCodeOwnerReviews=false RequiredApprovingReviewCount=1 RequiredLinearHistory=false AllowForcePushes=false AllowDeletions=false BlockCreations=false RequiredConversationResolution=false --stack-name=${{ github.head_ref }}-sam-set-branch-protection --resolve-s3 --capabilities CAPABILITY_IAM ##s3-bucket## --region ##region##